import { BiLink } from "react-icons/bi";
import { CiAt, CiWallet } from "react-icons/ci";
import { FaArrowRight, FaCaretUp, FaCheckCircle, FaEthereum, FaShieldAlt, FaSpinner, FaUsers } from "react-icons/fa";
import { FaCircleCheck, FaCircleInfo, FaCircleXmark } from "react-icons/fa6";
import { GiRoundStar } from "react-icons/gi";
import { HiInformationCircle, HiX } from "react-icons/hi";
import { ImSpinner8 } from "react-icons/im";
import { IoIosArrowBack, IoIosArrowForward, IoIosFitness, IoMdClose } from "react-icons/io";
import { IoCheckmark, IoCheckmarkOutline, IoCloseOutline, IoWarning } from "react-icons/io5";
import {
    LuArrowDownRight,
    LuArrowLeft,
    LuArrowRight,
    LuBuilding2,
    LuCalendar,
    LuCheck,
    LuChevronDown,
    LuChevronLeft,
    LuChevronRight,
    LuChevronUp,
    LuCircleUserRound,
    LuClock,
    LuEye,
    LuEyeOff,
    LuGlobe,
    LuMail,
    LuMapPin,
    LuPencilLine,
    LuPlus,
    LuSave,
    LuSearch,
    LuTrash2,
    LuX,
} from "react-icons/lu";
import { MdSportsGymnastics } from "react-icons/md";
import {
    PiAtom,
    PiBarbell,
    PiBrainLight,
    PiCalendarStarDuotone,
    PiEye,
    PiEyeSlashLight,
    PiFunnel,
    PiGearDuotone,
    PiGithubLogo,
    PiInfoFill,
    PiLinkedinLogo,
    PiLinkSimpleDuotone,
    PiShieldCheckDuotone,
    PiSignOut,
    PiSoundcloudLogoDuotone,
    PiSpotifyLogoDuotone,
    PiTwitterLogoDuotone,
    PiUserGearDuotone,
    PiUserPlusDuotone,
    PiUsersDuotone,
    PiRobotLight,
    PiHeartbeat,
    PiPlant,
    PiCoinVertical,
    PiPalette,
    PiLego,
    PiCreditCardDuotone,
    PiAppleLogoDuotone,
    PiGoogleLogoDuotone,
    PiPaperPlane,
    PiRocketLaunch,
    PiRocketLaunchDuotone,
    PiRocketLaunchFill,
    PiArrowUpRight,
    PiStarFour,
    PiCrown,
    PiCheckSquareDuotone,
    PiTrophyDuotone,
    PiRankingDuotone,
    PiHandPalmDuotone,
    PiUsersThreeDuotone,
    PiSparkle,
    PiXCircleFill,
    PiCrosshair,
} from "react-icons/pi";
import { RiLoader3Fill } from "react-icons/ri";
import { RxHamburgerMenu } from "react-icons/rx";
import { VscChromeClose } from "react-icons/vsc";
import { BuenosAiresIcon, HongKongIcon, LondonIcon, LosAngelesIcon, NewYorkIcon, TorontoIcon } from "./custom";

export const iconRegistry = {
    atom: PiAtom,
    arrowLeft: LuArrowLeft,
    arrowRight: LuArrowRight,
    arrowDownRight: LuArrowDownRight,
    arrowBack: IoIosArrowBack,
    arrowForward: IoIosArrowForward,
    arrowRightAlt: FaArrowRight,
    barbell: PiBarbell,
    caretUp: FaCaretUp,
    chevronRight: LuChevronRight,
    chevronLeft: LuChevronLeft,
    chevronDown: LuChevronDown,
    chevronUp: LuChevronUp,
    close: LuX,
    closeAlt: IoMdClose,
    closeAlt2: HiX,
    closeAlt3: VscChromeClose,
    closeAlt4: IoCloseOutline,
    add: LuPlus,
    save: LuSave,
    delete: LuTrash2,
    edit: LuPencilLine,
    search: LuSearch,
    filter: PiFunnel,
    menu: RxHamburgerMenu,

    check: LuCheck,
    checkmark: IoCheckmark,
    checkmarkOutline: IoCheckmarkOutline,
    checkCircle: FaCheckCircle,
    checkDuoTone: PiCheckSquareDuotone,
    creditCardDuotone: PiCreditCardDuotone,
    crown: PiCrown,
    appleDuotone: PiAppleLogoDuotone,
    googleDuotone: PiGoogleLogoDuotone,
    success: FaCircleCheck,
    info: FaCircleInfo,
    infoFill: PiInfoFill,
    infoHi: HiInformationCircle,
    error: FaCircleXmark,
    warning: IoWarning,
    star: GiRoundStar,
    starAlt: PiStarFour,
    shield: FaShieldAlt,
    shieldCheck: PiShieldCheckDuotone,

    eye: PiEye,
    eyeAlt: LuEye,
    eyeSlash: PiEyeSlashLight,
    eyeSlashAlt: LuEyeOff,
    signOut: PiSignOut,
    sparkle: PiSparkle,
    userRound: LuCircleUserRound,
    userPlus: PiUserPlusDuotone,
    userGear: PiUserGearDuotone,
    users: FaUsers,
    usersDuotone: PiUsersDuotone,
    usersThreeDuoTone: PiUsersThreeDuotone,
    wallet: CiWallet,

    calendar: LuCalendar,
    calendarStar: PiCalendarStarDuotone,
    clock: LuClock,
    building: LuBuilding2,
    globe: LuGlobe,
    mapPin: LuMapPin,
    mail: LuMail,
    at: CiAt,
    gear: PiGearDuotone,
    link: BiLink,
    linkSimple: PiLinkSimpleDuotone,
    loaderFill: RiLoader3Fill,

    github: PiGithubLogo,
    linkedin: PiLinkedinLogo,
    twitter: PiTwitterLogoDuotone,
    spotify: PiSpotifyLogoDuotone,
    soundcloud: PiSoundcloudLogoDuotone,

    spinner: ImSpinner8,
    spinnerAlt: FaSpinner,

    rankingDuoTone: PiRankingDuotone,

    thorphyDuoTone: PiTrophyDuotone,
    brain: PiBrainLight,
    robotLight: PiRobotLight,
    heartbeat: PiHeartbeat,
    plant: PiPlant,
    coin: PiCoinVertical,
    palette: PiPalette,
    fitness: IoIosFitness,
    gymnastics: MdSportsGymnastics,
    lego: PiLego,
    twitterDuotone: PiTwitterLogoDuotone,
    eth: FaEthereum,
    paperplane: PiPaperPlane,
    rocketLaunch: PiRocketLaunch,
    rocketLaunchDuotone: PiRocketLaunchDuotone,
    rocketLaunchFill: PiRocketLaunchFill,
    arrowUpRight: PiArrowUpRight,

    nextBuenosAires: BuenosAiresIcon,
    nextHongKong: HongKongIcon,
    nextLondon: LondonIcon,
    nextNewYork: NewYorkIcon,
    nextToronto: TorontoIcon,
    nextLosAngeles: LosAngelesIcon,

    handPalmDuotone: PiHandPalmDuotone,
    closeCircleFill: PiXCircleFill,
    crosshair: PiCrosshair,
} as const;

export type IconName = keyof typeof iconRegistry;

export const hasIcon = (name: string): name is IconName => {
    return name in iconRegistry;
};

export const getAvailableIcons = (): IconName[] => {
    return Object.keys(iconRegistry) as IconName[];
};
